application: vektornye
version: 1
runtime: python
api_version: 1

handlers:
- url: .(.*\.(svg))
  static_files: \1
  upload: .(.*\.(svg))

- url: .(.*\.(js))
  static_files: \1
  upload: .(.*\.(js))

- url: .(.*\.(png))
  static_files: \1
  upload: .(.*\.(png))

- url: /.*
  script: index.py